sudo: required
services:
 - docker

before_install:
  - docker build -t vncgrvs/docker-tut -f Dockerfile.dev .

script:
  - docker run -e CI=true vncgrvs/docker-tut npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-tut"
  env: "Dockertut-env"
  bucket_name: "elasticbeanstalk-us-east-2-665598725239"
  bucket_path: "docker-tut"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  
   