sudo: required
services:
 - docker

before_install:
  - docker build -t vncgrvs/react -f Dockerfile.dev .

script:
  - docker run -e CI=true vncgrvs/react npm run test -- --coverage

deploy:
  - provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-test"
    env: "Dockertest-env"
    bucket_name: "elasticbeanstalk-us-east-2-665598725239"
    bucket_path: "docker-test"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
  
  - provider: script
    script: bash run.sh $LIX_TOKEN



  
   