sudo: required
services:
 - docker

language: python

python:
  - "3.8.6"

install:
 - pip install -r req.txt


before_install:
  - docker build -t vncgrvs/react -f Dockerfile .

script:
  - docker run -e CI=true vncgrvs/react npm run test -- --coverage

deploy:
  - provider: elasticbeanstalk
    region: "us-east-2"
    app: "demo-csm"
    env: "Democsm-env"
    bucket_name: "elasticbeanstalk-us-east-2-129263247607"
    bucket_path: "demo-csm"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
  
  - provider: script
    script: python run.py token -t $LIX_TOKEN -r $TRAVIS_REPO_SLUG
    on:
      branch: master



  
   